#!/bin/bash

install_zsh_custom_plugins() {
  local ZSH_CUSTOM="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"
  local plugins=("$@")
  local dir

  exists git || {
    log_error "git not found. Skipping custom plugins."
    return 1
  }

  for plugin in "${plugins[@]}"; do
    case "$plugin" in
      zsh-autosuggestions)
        repo="https://github.com/zsh-users/zsh-autosuggestions"
        ;;
      zsh-syntax-highlighting)
        repo="https://github.com/zsh-users/zsh-syntax-highlighting"
        ;;
      *) continue ;; # Skip bundled plugins
    esac

    dir="$ZSH_CUSTOM/plugins/$plugin"
    if [ ! -d "$dir" ]; then
      log_info "Cloning $plugin..."
      git clone --depth 1 "$repo" "$dir"
    else
      log_info "Plugin $plugin already exists."
    fi
  done
}

update_zshrc_plugins() {
  local ZSHRC="$HOME/.zshrc"
  local plugins=("$@")

  [[ ! -f "$ZSHRC" ]] && {
    log_error "$ZSHRC not found"
    return 1
  }
  cp "$ZSHRC" "$ZSHRC.bak"

  # Find boundaries
  local START_LINE
  START_LINE=$(awk '/^plugins=\(/ {print NR; exit}' "$ZSHRC")
  local END_LINE
  END_LINE=$(awk -v start="$START_LINE" 'NR >= start && /\)/ {print NR; exit}' "$ZSHRC")

  if [[ -z "$START_LINE" || -z "$END_LINE" ]]; then
    log_warn "No plugins block found. Creating new one at EOF."
    {
      echo -e "\nplugins=("
      for p in "${plugins[@]}"; do echo "  $p"; done
      echo ")"
    } >> "$ZSHRC"
    return
  fi

  # Rebuild the file safely
  {
    head -n "$((START_LINE - 1))" "$ZSHRC"
    echo "plugins=("
    for p in "${plugins[@]}"; do echo "  $p"; done
    echo ")"
    tail -n +$((END_LINE + 1)) "$ZSHRC"
  } > "$ZSHRC.tmp" && mv "$ZSHRC.tmp" "$ZSHRC"

  log_success "Updated Zsh plugins in $ZSHRC."
}

install_zsh_plugins() {
  # Read plugins from YAML into a bash array
  # mapfile is great, but for cross-platform (older bash), use this:
  local plugins
  # shellcheck disable=SC2207
  plugins=($(read_conf '.terminal.plugins[]' config.yaml))

  # Install external ones
  install_zsh_custom_plugins "${plugins[@]}"

  # Write to .zshrc
  update_zshrc_plugins "${plugins[@]}"
}

install_oh_my_zsh() {
  if config_enabled "terminal.oh_my_zsh" && [[ ! -d "$HOME/.oh-my-zsh" ]]; then
    log_info "Installing Oh My Zsh..."
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  fi
}

install_zsh_theme() {
  local theme
  theme=$(read_conf ".terminal.theme")
  log_info "Configuring Zsh theme: $theme"

  case "$theme" in
    "powerlevel10k")
      if [[ "$IS_MAC" == true ]]; then
        install_pkg "powerlevel10k"
        # shellcheck disable=SC2016
        ensure_line 'source $(brew --prefix)/share/powerlevel10k/powerlevel10k.zsh-theme' "$HOME/.zshrc"
      else
        # Linux/Manual fallback
        local target="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"
        [[ ! -d "$target" ]] && git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "$target"
        replace_or_add "ZSH_THEME=" "ZSH_THEME=\"powerlevel10k/powerlevel10k\"" "$HOME/.zshrc"
      fi
      ;;

    "spaceship" | "dracula")
      # Custom themes that need to be cloned into OMZ custom folder
      local target="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/$theme"
      if [[ ! -d "$target" ]]; then
        log_info "Cloning $theme theme..."
        git clone "https://github.com/${theme}/${theme}.git" "$target"
      fi
      # Update .zshrc to point to the new theme
      replace_or_add "ZSH_THEME=" "ZSH_THEME=\"$theme\"" "$HOME/.zshrc"
      ;;

    *)
      # Default: Assume it's a built-in Oh My Zsh theme (like 'robbyrussell')
      log_info "Setting built-in theme: $theme"
      replace_or_add "ZSH_THEME=" "ZSH_THEME=\"$theme\"" "$HOME/.zshrc"
      ;;
  esac
}

install_aliases() {
  log_info "--- Configuring Shell Aliases ---"

  local alias_file="$HOME/.zsh_aliases"

  # Start with a clean header in the alias file
  echo "# Auto-generated aliases from dotfiles setup" > "$alias_file"
  echo "# Do not edit this file manually; update config.yaml instead" >> "$alias_file"
  echo "" >> "$alias_file"

  # Extract keys and values from config.yaml
  # We use yq to get the keys (gs, art, etc.)
  local alias_keys
  alias_keys=$(read_conf '.terminal.aliases | keys | .[]' config.yaml)

  for key in $alias_keys; do
    # Get the value for each key
    local value
    value=$(read_conf ".terminal.aliases.\"$key\"" config.yaml)

    log_info "Adding alias: $key -> $value"
    ensure_line "alias -- $key=\"$value\"" "$alias_file"
  done

  # Ensure the alias file is sourced in .zshrc
  ensure_line "[ -f \"$alias_file\" ] && source \"$alias_file\"" "$HOME/.zshrc"

  log_success "Aliases synced to $alias_file"
}
